# Generated by Django 2.0.6 on 2018-06-16 15:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_auto_20180615_2233'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='first_name',
            field=models.CharField(default=' ', help_text='First name', max_length=200),
        ),
        migrations.AddField(
            model_name='booking',
            name='last_name',
            field=models.CharField(default=' ', help_text='Last name', max_length=200),
        ),
        migrations.AlterField(
            model_name='booking',
            name='number_of_tickets',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(1, 'Mindestens ein Ticket'), django.core.validators.MaxValueValidator(5, 'Maximal 5 Tickets pro Buchung erlaubt')]),
        ),
    ]
