# Generated by Django 2.0.6 on 2018-06-16 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_auto_20180616_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='first_name',
            field=models.CharField(help_text='First name', max_length=200),
        ),
        migrations.AlterField(
            model_name='booking',
            name='last_name',
            field=models.CharField(help_text='Last name', max_length=200),
        ),
    ]
