# Generated by Django 2.0.6 on 2018-06-16 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='code',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
    ]
